server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/course/**

  # Swagger configuration
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      urls:
        - name: "Students API"
          url: "http://localhost:8090/v3/api-docs"  # Swagger URL for the students service
        - name: "Courses API"
          url: "http://localhost:9090/v3/api-docs"  # Swagger URL for the courses service

  # Actuator configuration
  management:
    endpoints:
      web:
        exposure:
          include: "health,info,metrics,prometheus,swagger"
    endpoint:
      health:
        show-details: always

eureka:
  client:
    register-with-eureka: false